const WHATSAPP_COUNTRY_CODE = "32";
const WHATSAPP_NUMBER = "400012234";
const WHATSAPP_MESSAGE = "Hallo D Reynders Projects, ik heb een vraag over een plat dak.";

document.addEventListener("DOMContentLoaded", () => { setupWhatsAppLinks(); setupMobileNavigation(); setupDynamicYear(); setupNetlifyForm(); setupImageFallbacks(); setupActiveNavigation(); });
function setupWhatsAppLinks(){const links=document.querySelectorAll(".js-whatsapp");const url=`https://wa.me/${WHATSAPP_COUNTRY_CODE.replace(/\D/g,"")}${WHATSAPP_NUMBER.replace(/\D/g,"")}?text=${encodeURIComponent(WHATSAPP_MESSAGE)}`;links.forEach(l=>{l.href=url;l.target="_blank";l.rel="noopener"})}
function setupMobileNavigation(){const t=document.querySelector(".nav-toggle"),n=document.querySelector(".site-nav");if(!t||!n)return;t.addEventListener("click",()=>{const o=t.getAttribute("aria-expanded")==="true";t.setAttribute("aria-expanded",String(!o));t.classList.toggle("is-open",!o);n.classList.toggle("is-open",!o)});n.addEventListener("click",e=>{if(!e.target.matches("a"))return;t.setAttribute("aria-expanded","false");t.classList.remove("is-open");n.classList.remove("is-open")});document.addEventListener("keydown",e=>{if(e.key!=="Escape")return;t.setAttribute("aria-expanded","false");t.classList.remove("is-open");n.classList.remove("is-open")})}
function setupDynamicYear(){document.querySelectorAll(".js-year").forEach(e=>e.textContent=new Date().getFullYear())}
function setupNetlifyForm(){const f=document.querySelector('form[name="contact"]');if(!f)return;const m=f.querySelector(".form-message"),b=f.querySelector('button[type="submit"]');f.addEventListener("submit",async e=>{e.preventDefault();if(!f.checkValidity()){f.reportValidity();showFormMessage(m,"error","Vul de verplichte velden aan en probeer opnieuw.");return}const d=new URLSearchParams(new FormData(f));if(b){b.disabled=true;b.textContent="Bezig met verzenden..."}try{const r=await fetch("/",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:d.toString()});if(!r.ok)throw new Error("Form submission failed");f.reset();showFormMessage(m,"success","Bedankt voor uw bericht. We nemen contact met u op om uw vraag te bespreken.")}catch(err){showFormMessage(m,"error","Er ging iets mis bij het verzenden. Probeer opnieuw of neem telefonisch contact op.")}finally{if(b){b.disabled=false;b.textContent="Verstuur uw vraag"}}})}
function showFormMessage(e,t,x){if(!e)return;e.textContent=x;e.classList.remove("is-success","is-error");e.classList.add(t==="success"?"is-success":"is-error")}
function setupImageFallbacks(){document.querySelectorAll("img").forEach(i=>i.addEventListener("error",()=>{const f=i.closest("figure");if(f)f.classList.add("image-missing");i.alt="Beeld volgt"}))}
function setupActiveNavigation(){const links=document.querySelectorAll(".site-nav a[href^='#']");const items=Array.from(links).map(link=>{const section=document.querySelector(link.getAttribute("href"));return section?{link,section}:null}).filter(Boolean);if(!items.length||!("IntersectionObserver" in window))return;const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(!entry.isIntersecting)return;const active=items.find(i=>i.section===entry.target);links.forEach(l=>l.classList.remove("is-active"));if(active)active.link.classList.add("is-active")})},{rootMargin:"-35% 0px -55% 0px"});items.forEach(i=>observer.observe(i.section))}
